# TravisCI config file. See http://travis-ci.org
language: python

python:
  - 2.7

# environment variables
env: MYSQL_TEST_HOST=127.0.0.1 MYSQL_TEST_USER=travis MYSQL_TEST_PASSWORD='' MYSQL_TEST_DB=b3_test POSTGRESQL_TEST_HOST=127.0.0.1 POSTGRESQL_TEST_USER=postgres POSTGRESQL_TEST_PASSWORD='' POSTGRESQL_TEST_DB=b3_test

# select postgresql version
addons:
  postgresql: "9.3"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r optional-requirements.txt
  - pip install -r test-requirements.txt
  - pip install -r build-requirements.txt

before_script:
  - psql -c "CREATE DATABASE b3_test WITH OWNER = postgres ENCODING = 'UTF8';" -U postgres

# command to run tests, e.g. python setup.py test
script: 
  - nosetests --where=tests --verbosity=3 --with-cov --cov b3 --cov-report term-missing --cov-config .coveragerc
  - python setup.py egg_info --tag-build .dev${TRAVIS_COMMIT:0:7} --tag-date sdist bdist_wheel
  - python setup.py build_exe

after_success:
  - pip install coveralls
  - coveralls

deploy:
  provider: s3
  access_key_id: $s3_access_key_id
  secret_access_key: $s3_secret_access_key
  bucket: "b3-travis-artifacts"
  skip_cleanup: true
  acl: public_read
  region: eu-west-1
  local_dir: dist

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/489374443a557d989111
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
